[config]
absolute_center_x = 640
absolute_center_y = 480
repeat_delay = 16
mouse_delay = 16
repeat_rate = 60
mouse_slow_scale = 40
deadzone_mode = scaled_radial
deadzone_scale = 8
deadzone_x = 2000
deadzone_y = 2000
deadzone_triggers = 3000
dpad_mouse_normalize = true

[controls]
overlay = clear

dpad = mouse_movement

; swap the comments below to use absolute mouse
left_analog = mouse_movement
; left_analog = mouse_absolute

right_analog_up = "up"
right_analog_down = "down"
right_analog_left = "left"
right_analog_right = "right"

a = "mouse_left" ; pointer click
b = "mouse_right" ; walk / run
x = "q" ; jump
y = "f10" ; switch equipped weapons

select = "esc"
start = hold_state hotkey_start_group
guide = "q" ; invert spell

l1 = hold_state hotkey_spell_group
l2 = "mouse_slow" ;"mouse_right"
r1 = "shift" ; invert spell
r2 = "mouse_left"   ; secondary way to do weapon
